version: '2'
services:
    app:
        build: app
        image: niwenhao/senju_app
        hostname: app
        container_name: app
        volumes:
            - ${HOME}/workspace/senju-test-compose/SenjuTest:/home/dev/SenjuTest:rw
            - ${HOME}/myhome/_vimrc:/home/dev/.vimrc
            - ${HOME}/myhome/_vim:/home/dev/.vim
            - /etc/rootca.crt:/etc/rootca.crt
        env_file: /etc/environment
        links:
            - db
        expose:
            - 3000
        command: bash -c 'while true; do sleep 10; done'
        networks:
          app_net:
            ipv4_address: 172.21.1.10
    db:
        #build: db
        image: postgres
        environment:
            POSTGRES_USER: senju
            POSTGRES_DB: senjudb
            POSTGRES_PASSWORD: password
        volumes:
          - ${HOME}/workspace/senju-test-compose/pgdata:/var/lib/postgresql/data
        hostname: db
        container_name: db
        networks:
          app_net:
            ipv4_address: 172.21.1.11

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.1.0/24
          gateway: 172.21.1.1
