# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e034df14f5c52834ef0da5cea3d4a3500ce207c3c85d6d503962b1039de3ea687e883fa39024d71c726d9cd56b5e156054dd9ce4a23045ccb6baa53bcc8591a

test:
  secret_key_base: eef72bb01de5369386993370468ff3d88ac49d44227b98a47d50c6ef5f84ee2e66d70fd2cd1e9b7d18114b943530b8126db59db7d2bd2bf0dacebc9b062cf76b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
