from niwenhao/ruby

run apt-get update
run apt-get upgrade -y
run apt-get install -y postgresql-client
run apt-get install -y csh
run apt-get install -y libpq-dev
run apt-get install -y openjdk-7-jdk
run gem install bundle
